apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-output-nfs-pvc
  namespace: argo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: argo-output--nfs-pv
  storageClassName: ""