apiVersion: v1
kind: PersistentVolume
metadata:
  name: ofo-share-nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.205.254
    path: /ofo-share-serve