apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 
  namespace: argo
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: ofo-share-nfs-pv
  storageClassName: ""